# Generated by Django 3.0.1 on 2019-12-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.crm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'ВИК'), ('2', 'ПВК'), ('3', 'РК'), ('4', 'УК'), ('5', 'МК'), ('6', 'ПВТ'), ('7', 'Образцы, эталоны'), ('8', 'Вспомогательное оборудование'), ('9', 'Расходники')], default=1, max_length=50, null=True, verbose_name='Нормативно-техническая документация')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('factory_number', models.CharField(max_length=50, verbose_name='Заводской номер')),
                ('purpose', models.CharField(blank=True, max_length=250, null=True, verbose_name='Назначение')),
                ('year_of_manufacture', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год изготовления')),
                ('manufacture', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изготовитель')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Владелец')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительня информация')),
                ('place_of_verification', models.CharField(max_length=50, verbose_name='Место проведения поверки')),
                ('date_of_verification', models.DateField(verbose_name='Дата поверки')),
                ('validity', models.DateField(verbose_name='Дата окончания поверки')),
                ('status', models.CharField(blank=True, choices=[('И', 'Исправны (используют в работе)'), ('К', 'Законсервированы (в работе не используют)'), ('Р', 'Подлежат ремонту'), ('С', 'Подлежат списанию')], default=1, max_length=50, null=True, verbose_name='Нормативно-техническая документация')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ntd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Нормативно-техническая документация',
                'verbose_name_plural': 'Нормативно-техническая документация',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Разрешенная документация',
                'verbose_name_plural': 'Разрешенная документация',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=modules.crm.models.path_file, verbose_name='Квалификационное удостоверение')),
                ('docs', models.FileField(blank=True, null=True, upload_to=modules.crm.models.path_file, verbose_name='Дополнительные документы')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь EMIS')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate', models.CharField(max_length=150, verbose_name='Дирекция')),
                ('contractor', models.CharField(max_length=50, verbose_name='Заказчик')),
                ('ntd', models.CharField(blank=True, choices=[('1', 'НТД-1'), ('2', 'НТД-2'), ('3', 'НТД-3')], default=1, max_length=50, null=True, verbose_name='Нормативно-техническая документация')),
                ('rd', models.CharField(blank=True, choices=[('1', 'РД-1'), ('2', 'РД-2'), ('3', 'РД-3')], default=1, max_length=50, null=True, verbose_name='Разрешенная документация')),
                ('project', models.FileField(upload_to=modules.crm.models.path_file, verbose_name='Проект')),
                ('personnel', models.ManyToManyField(to='crm.Personnel', verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
