# Generated by Django 3.0.1 on 2019-12-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='User',
            new_name='user',
        ),
    ]
