# Generated by Django 3.0.1 on 2019-12-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191224_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='rd',
            options={'verbose_name': 'Разрешенная документация', 'verbose_name_plural': 'Разрешенная документация'},
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Важная информация'),
        ),
        migrations.AddField(
            model_name='entity',
            name='equipment',
            field=models.ManyToManyField(to='crm.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[('И', 'Исправны (используют в работе)'), ('К', 'Законсервированы (в работе не используют)'), ('Р', 'Подлежат ремонту'), ('С', 'Подлежат списанию')], default=1, max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'ВИК'), ('2', 'ПВК'), ('3', 'РК'), ('4', 'УК'), ('5', 'МК'), ('6', 'ПВТ'), ('7', 'Образцы, эталоны'), ('8', 'Вспомогательное оборудование'), ('9', 'Расходники')], default=1, max_length=50, null=True, verbose_name='Тип'),
        ),
    ]
