# Generated by Django 3.0.1 on 2019-12-26 23:39

from django.db import migrations, models
import modules.crm.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contractor',
            field=models.CharField(help_text='Введите название заказчика', max_length=50, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='crm.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='personnel',
            field=models.ManyToManyField(blank=True, null=True, to='crm.Personnel', verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='project',
            field=models.FileField(blank=True, null=True, upload_to=modules.crm.models.path_file, verbose_name='Проект'),
        ),
    ]
