# Generated by Django 3.0.1 on 2019-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0006_auto_20191230_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
    ]
