# Generated by Django 3.0.1 on 2020-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200106_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='date_of_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place_of_verification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место проведения поверки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[('И', 'Исправны (используют в работе)'), ('К', 'Законсервированы (в работе не используют)'), ('Р', 'Подлежат ремонту'), ('С', 'Подлежат списанию')], default='И', max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='validity',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания поверки'),
        ),
    ]
