# Generated by Django 3.0.1 on 2020-01-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200106_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='factory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводской номер'),
        ),
    ]
