# Generated by Django 3.0.1 on 2020-02-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200115_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='director_lnr',
            field=models.CharField(blank=True, help_text='Введите название руководитель ЛНК', max_length=50, null=True, verbose_name='руководитель ЛНК'),
        ),
    ]
