# Generated by Django 3.0.1 on 2020-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20200218_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Важная информация'),
        ),
    ]
