# Generated by Django 3.0.1 on 2020-08-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0016_personnel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.CharField(max_length=150)),
                ('row2', models.CharField(max_length=150)),
                ('row3', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Вид контроля',
                'verbose_name_plural': 'Вид контроля',
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='crm.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='files',
            field=models.ManyToManyField(blank=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='personnel',
            field=models.ManyToManyField(blank=True, to='crm.Personnel', verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='files',
            field=models.ManyToManyField(blank=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='files',
            field=models.ManyToManyField(blank=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField()),
                ('level', models.IntegerField(blank=True, null=True)),
                ('cert_center', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Аттистационный центер')),
                ('control', models.ManyToManyField(blank=True, to='crm.TypeControl', verbose_name='Вид контроля')),
                ('file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.Attachment', verbose_name='Загрузка удостоверения')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Personnel', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Удостоверение',
                'verbose_name_plural': 'Удостоверения',
            },
        ),
        migrations.CreateModel(
            name='AdditionalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date1', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('cert_center', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Аттистационный центер')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.Attachment', verbose_name='Загрузка удостоверения')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Personnel', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Дополнительное удостоверение',
                'verbose_name_plural': 'Дополнительные удостоверения',
            },
        ),
    ]
