# Generated by Django 3.0.1 on 2020-08-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0017_auto_20200823_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalidentity',
            old_name='file',
            new_name='_file',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='file',
        ),
        migrations.AddField(
            model_name='identity',
            name='_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.Attachment', verbose_name='Загрузка удостоверения'),
        ),
    ]
