# Generated by Django 3.0.1 on 2020-08-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20200823_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
    ]
