# Generated by Django 3.0.1 on 2020-08-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0019_remove_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalidentity',
            name='_file',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_manager.Attachment', verbose_name='Загрузка удостоверения'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='_file',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_manager.Attachment', verbose_name='Загрузка удостоверения'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='cert_center',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Аттистационный центр'),
        ),
        migrations.AlterField(
            model_name='typecontrol',
            name='row1',
            field=models.CharField(max_length=150, verbose_name='Вид контроля'),
        ),
        migrations.AlterField(
            model_name='typecontrol',
            name='row2',
            field=models.CharField(max_length=150, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='typecontrol',
            name='row3',
            field=models.CharField(max_length=150, verbose_name='Объекты контроля'),
        ),
    ]
