# Generated by Django 3.0.1 on 2020-08-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0020_auto_20200827_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('1', 'Информирование'), ('2', 'Перемещение'), ('3', 'Ремонт'), ('4', 'Иное')], default=1, max_length=50, null=True, verbose_name='Вид операции')),
                ('comment', models.CharField(max_length=1000)),
                ('_file', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_manager.Attachment', verbose_name='Файл')),
                ('entity', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Entity', verbose_name='Объект')),
                ('equipment', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'История перемещений',
                'verbose_name_plural': 'История перемещений',
            },
        ),
    ]
