# Generated by Django 3.0.1 on 2020-08-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0021_auto_20200828_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalidentity',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='history',
            name='_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_manager.Attachment', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='history',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Entity', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='history',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_manager.Attachment', verbose_name='Загрузка удостоверения'),
        ),
    ]
