# Generated by Django 3.1.6 on 2021-02-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20200830_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[('И', 'Исправны (используют в работе)'), ('К', 'Законсервированы (в работе не используют)'), ('Р', 'Подлежат ремонту'), ('С', 'Подлежат списанию')], max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'ВИК'), ('2', 'ПВК'), ('3', 'РК'), ('4', 'УК'), ('5', 'МК'), ('6', 'ПВТ'), ('7', 'Образцы, эталоны'), ('8', 'Вспомогательное оборудование'), ('9', 'Расходники')], max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.department', verbose_name='Отдел'),
        ),
    ]
