# Generated by Django 3.1.6 on 2021-02-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20210223_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='personnel',
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Руководитель подразделения ЛНК'), ('2', 'Состав подразделения ЛНК'), ('3', 'Персонал взоимодействия')], default=1, max_length=50, verbose_name='Подразделение')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.personnel', verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='subdivision',
            field=models.ManyToManyField(blank=True, to='crm.Subdivision', verbose_name='Подразделение'),
        ),
    ]
