# Generated by Django 3.1.6 on 2021-02-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210227_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.personnel', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='type',
            field=models.CharField(choices=[('1', 'Руководитель подразделения ЛНК'), ('2', 'Состав подразделения ЛНК'), ('3', 'Персонал взоимодействия')], default=2, max_length=50, verbose_name='Подразделение'),
        ),
        migrations.AlterModelTable(
            name='entity',
            table=None,
        ),
    ]
