# Generated by Django 3.1.6 on 2021-02-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20210227_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='subdivision',
        ),
    ]
