# Generated by Django 3.1.6 on 2021-03-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_entity_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Обьект'),
            preserve_default=False,
        ),
    ]
