# Generated by Django 3.1.6 on 2021-03-27 23:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_subdivision_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['type']},
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Доп. телефон 1'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Доп. телефон 2'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='personnel',
            field=models.ManyToManyField(blank=True, to='crm.Personnel', verbose_name='Сотрудник'),
        ),
    ]
