# Generated by Django 3.1.6 on 2021-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20210328_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalidentity',
            name='cert_center',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Аттестационный центр'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='cert_center',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Аттестационный центр'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='type',
            field=models.CharField(choices=[('1', 'Руководитель подразделения ЛНК'), ('2', 'Состав подразделения ЛНК'), ('3', 'Персонал взаимодействия')], default=2, max_length=50, verbose_name='Подразделение'),
        ),
    ]
