# Generated by Django 3.1.7 on 2022-01-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0030_auto_20210328_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=4, verbose_name='Атрибут')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус оборудования',
                'verbose_name_plural': 'Статусы оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, verbose_name='Номер типа')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.AlterField(
            model_name='additionalidentity',
            name='_file',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.attachment', verbose_name='Загрузка удостоверения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'ВИК'), ('2', 'ПВК'), ('3', 'РК'), ('4', 'УК'), ('5', 'МК'), ('6', 'ПВТ'), ('7', 'ЭК'), ('8', 'Вспомогательное'), ('9', 'Мера'), ('10', 'Образец'), ('11', 'Эталон'), ('12', 'Дозиметрия')], max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='history',
            name='_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.attachment', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='history',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='history',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.equipment', verbose_name='Оборудование'),
        ),
    ]
