# Generated by Django 3.1.7 on 2022-03-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20220327_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
