# Generated by Django 3.1.7 on 2023-04-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_delete_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Код ОКЗ',
                'verbose_name_plural': 'Коды ОКЗ',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Руководитель подразделения ЛНК'), ('2', 'Состав подразделения ЛНК'), ('3', 'Персонал взаимодействия')], default=2, max_length=50, verbose_name='Подразделение')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Обьект')),
                ('personnel', models.ManyToManyField(blank=True, to='crm.Personnel', verbose_name='Сотрудник')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=64, verbose_name='Табель')),
                ('period', models.CharField(blank=True, max_length=70, null=True, verbose_name='Период')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Обьект')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.personnel', verbose_name='Ответственный')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табеля',
            },
        ),
        migrations.CreateModel(
            name='HistoryTabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='№ п/п')),
                ('salary', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заработная плата')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание работы')),
                ('salary_work', models.CharField(blank=True, max_length=64, null=True, verbose_name='Зар. плата за отработанные дни')),
                ('payment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Оплата медицинского обследования, проезда')),
                ('award', models.CharField(blank=True, max_length=64, null=True, verbose_name='Премия')),
                ('accrued', models.CharField(blank=True, max_length=64, null=True, verbose_name='Начислено')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.personnel', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Список табелей',
                'verbose_name_plural': 'Списки табелей',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала договора')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('service_provide', models.TextField(blank=True, null=True, verbose_name='Содержание оказываемых услуг')),
                ('mark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.code', verbose_name='Код ОКЗ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Обьект')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.code', verbose_name='Код ОКЗ'),
        ),
    ]
