# Generated by Django 3.1.7 on 2023-04-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('crm', '0034_auto_20230416_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytabel',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='historytabel',
            name='report_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.reportcard', verbose_name='Табель'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='files',
            field=models.ManyToManyField(blank=True, to='files_manager.Attachment', verbose_name='Файлы'),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
