# Generated by Django 3.1.7 on 2023-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20230427_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytabel',
            name='penalty',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Штраф'),
        ),
    ]
