# Generated by Django 3.1.7 on 2023-05-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_historytabel_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytabel',
            name='penalty',
        ),
    ]
