# Generated by Django 3.1.7 on 2023-05-09 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_historytabel_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='crm.personnel', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='crm.personnel', verbose_name='Ответственный'),
        ),
    ]
