# Generated by Django 3.1.7 on 2023-05-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20230509_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
