# Generated by Django 4.2.1 on 2023-05-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0043_historytabel_work_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytabel',
            name='contract_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='additionalidentity',
            name='_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_manager.attachment', verbose_name='Загрузка удостоверения'),
        ),
        migrations.AlterField(
            model_name='historytabel',
            name='number',
            field=models.IntegerField(max_length=64, verbose_name='№ п/п'),
        ),
    ]
