# Generated by Django 4.2.1 on 2023-09-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_historytabel_contract_number_reportcard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
