# Generated by Django 4.2.1 on 2023-11-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_reportcard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.department', verbose_name='Отдел'),
        ),
    ]
