# Generated by Django 4.2.1 on 2023-11-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_equipment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='status',
            field=models.CharField(blank=True, choices=[('Р', 'Работает'), ('М', 'Межвахта'), ('У', 'Уволен')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
