# Generated by Django 4.2.1 on 2023-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_personnel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytabel',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
