# Generated by Django 4.2.1 on 2023-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_historytabel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='is_edit_history_tabel',
            field=models.BooleanField(default=True),
        ),
    ]
