# Generated by Django 3.0.1 on 2020-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20200828_2202'),
        ('profiles', '0002_customuser_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.ManyToManyField(blank=True, to='crm.History', verbose_name='История'),
        ),
    ]
