# Generated by Django 4.2.1 on 2023-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_historytabel_contract_number_reportcard_user_and_more'),
        ('profiles', '0004_auto_20210328_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='department_user', to='crm.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='entity',
            field=models.ManyToManyField(blank=True, related_name='entity_user', to='crm.entity', verbose_name='Объект'),
        ),
    ]
