version: '3.5'
services:
  django:
    build: .
    image: &app gitlab.it-rs.ru:5005/emis/emis_backend:latest
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - .env
    environment:
      - DEBUG=True      
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "postgres:14"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_dump:/backup
